host: "http://192.168.61.114:30702"
api_key: &reqres_key "V2xoc1MySkhWa2xSYmtKcVlsWmFObE5YY0habFJUVTJWMWhrVDJGclJqVlVNVkp1VFRCNFJGTnViRnBXZWxaeVdXcEpkMkZWT1hGUldGWlBaV3RWTVZSdWNFNU5SVFZWVjFSV1QyVnRUVEJVYkZKdVl6QnNkVlJ1UW1GTmFsSndWREpzUzJGVk5UWlJiVEZRVWtkb2NGUnJVazVsYXpGWVZXMXdXbVZyTVRaWGJGSktUa1V4VlZadGJGcE5hM0IwVkZaU1ZrMUZOVFpTV0doT1ZqRnJNVmRVU2xabFJuQlZWbFJHV2xZd1ZYcFhXSEJ5WlZad2NXRXpiRkJTTVVWNFZEQlNUMkZWTlZoVVdHeGhVa1pLYzFSdGNHRmhNR3gxVFVRd1BRPT0="

use_csv: true              # enable CSV-driven data
csv_file: "keywords.csv"   # CSV file name
csv_mode: "random"         # "random" or "sequential"
csv_column: ["keyword"]    # list of CSV columns to read

users:
  - name: customer
    weight: 6
    wait_time: [1, 3]
    sequential: true

    tasks:

      - method: GET
        endpoint: "/aes/api/v1/products/tag-suggestions"
        weight: 1
        params:
          query: "phone"
        headers:
          sxsrf: *reqres_key

      - method: GET
        endpoint: "/aes/api/v1/products/search"
        weight: 1
        headers:
          sxsrf: *reqres_key
        params:
          keyword: "{{keyword}}"    # placeholder will be replaced by CSV value
          sorting: 0
          rowsPerPage: 30
          currentPage: 1
          brandSlug: ""
          categoryName: ""
          maximumPrice: 1000000
          minimumPrice: 0
          rating: 0
        print_response: true         # log response body, headers, and status
